name: Varbase API Base
description: A recipe to set up JSON:API with authentication, authorization, and OpenAPI documentation for easy content ingestion by other applications.
type: Varbase API
install:
  - jsonapi
  - openapi
  - openapi_jsonapi
  - openapi_rest
  - openapi_ui_redoc
  - openapi_ui_swagger
  - simple_oauth
  - restui
  - jsonapi_extras
  - jsonapi_defaults
config:
  import:
    jsonapi: '*'
    openapi: '*'
    openapi_jsonapi: '*'
    openapi_rest: '*'
    openapi_ui_redoc: '*'
    openapi_ui_swagger: '*'
    simple_oauth: '*'
    restui: '*'
    jsonapi_extras: '*'
    jsonapi_defaults: '*'
  actions:
    jsonapi_extras.settings:
      simpleConfigUpdate:
        path_prefix: api
        include_count: false
        default_disabled: true
        validate_configuration_integrity: true
    user.role.site_admin:
      grantPermissions:
        - 'administer simple_oauth entities'
